export const Messages = {
  USER_CREATED: 'User created. Please verify your email by entering the OTP sent to your email.',
  USER_EXISTS: 'User with this email already exists.',
  USER_BLOCKED: 'User Blocked..!',
  OTP_INVALID: 'Invalid OTP or OTP has expired.',
  OTP_SENT: 'OTP has been sent to your mail',
  USER_NOT_FOUND: 'User not found.',
  EMAIL_VERIFIED: 'Email verified successfully!',
  INVALID_PASSWORD: 'Invalid password.',
  VERIFY_EMAIL: 'Please verify your email before logging in.',
  UNKNOWN_ERROR: 'An unknown error occurred.',
  USER_UPDATED: 'User updated successfully.',
  RECRUITER_CREATED: 'Recruiter created. Please verify your email by entering the OTP sent to your email.',
  LOGIN_SUCCESS: 'Login successful',
  LOGOUT_SUCCESS: "Logout successful",
  INVALID_DATA_PROVIDED: 'Invalid data provided.',
  INVALID_ORDER_ID_PROVIDED: 'Invalid Order Id provided.',
  USER_ID_REQUIRED: 'User ID is required.',
  PASSWORD_LENGTH: 'Password must be at least 8 characters long.',
  PASSWORD_COMMEN: 'Password is too common or easily guessable.',
  APPLICATION_SUCCESSFUL: 'Application successful.',
  REFRESH_TOKEN_MISSING: 'Refresh token missing',
  INVALID_OR_EXPIRED_REFRESH_TOKEN: 'Invalid or expired refresh token',
  RECRUITER_NOT_FOUND: 'Recruiter not found.',
  USER_BLOCKED_OR_UNBLOCKED: 'User blocked or unblocked successfully.',
  RESET_LINK_SENT: "Password reset link has been sent to your email.",
  RESET_TOKEN_INVALID: "Reset token is invalid or has expired.",
  PASSWORD_NOT_MATCH: "New password and confirm password do not match.",
  INVALID_CURRENT_PASSWORD: 'The current password you entered is incorrect. Please try again',
  PASSWORD_RESET_SUCCESS: "Your password has been reset successfully",
  INVALID_USER_ID: 'Invalid user ID provided.',
  GOOGLE_ACCOUNT: "This account is linked with Google. Cannot reset password.",
  USER_FOUND: 'User found',
  DUBLICATE_PRODUCT: 'Product Alredy Existing',
  DUBLICATE_PRODUCT_IN_CART: 'Product already in cart or cart contains items from another hotel.',
  PRODUCT_NOT_FOUND: 'Product Not found',
  PRODUCT_ID_NOT_FOUND: 'Product id Not found',
  MESSAGES_REQUIRED: 'Both old and new passwords are required.',
  OTP_VERIFIED: 'OTP verified successfully',
  SERVER_ERR: 'Internal server erorr',
  INVALID_REQUST: 'Invalid request',
  EMAIL_REQUIRED: 'Email required',
  INVALID_CREDENTIALS: 'Invalid credentials',
};