export const Messages = {
  USER_CREATED: 'User created. Please verify your email by entering the OTP sent to your email.',
  USER_EXISTS: 'User with this email already exists.',
  OTP_INVALID: 'Invalid OTP or OTP has expired.',
  OTP_SENT:     'OTP has been sent to your mail',
  USER_NOT_FOUND: 'User not found.',
  EMAIL_VERIFIED: 'Email verified successfully!',
  INVALID_PASSWORD: 'Invalid password.',
  VERIFY_EMAIL: 'Please verify your email before logging in.',
  UNKNOWN_ERROR: 'An unknown error occurred.',
  USER_UPDATED: 'User updated successfully.',
  RECRUITER_CREATED: 'Recruiter created. Please verify your email by entering the OTP sent to your email.',
  LOGIN_SUCCESS: 'Login successful',
  INVALID_DATA_PROVIDED: 'Invalid data provided.',
  USER_ID_REQUIRED: 'User ID is required.',
  PASSWORD_LENGTH:'Password must be at least 6 characters long.',
  PASSWORD_COMMEN:'Password is too common or easily guessable.',
  APPLICATION_SUCCESSFUL: 'Application successful.',
  REFRESH_TOKEN_MISSING: 'Refresh token missing',
  INVALID_OR_EXPIRED_REFRESH_TOKEN: 'Invalid or expired refresh token',
  RECRUITER_NOT_FOUND: 'Recruiter not found.', 
  USER_BLOCKED_OR_UNBLOCKED: 'User blocked or unblocked successfully.', 
  INVALID_USER_ID: 'Invalid user ID provided.',
  APPLIED_ALREADY:'You have already applied for this job.',
  USER_FOUND: 'User found',
  MESSAGES_REQUIRED:'Both old and new passwords are required.',
  OTP_VERIFIED: 'OTP verified successfully',
  SERVER_ERR:'Internal server erorr',
  INVALID_REQUST:'Invalid request'
};